### ISSUE TITLE
Shutdown Dependency-Track

### ISSUE THREAD

**Issue by patheard** [cds-snc/security-tools#182]
## Summary
With GitHub auto indexing our manifests and cds-snc/platform-core-services#204 nearly complete, Dependency-Track can be shutdown.

The reason for this is that we're now getting the following through GitHub:
- `Security`: vulnerability alerts for assets and Docker images
- `Dependency graph`: asset inventory of all packages and Docker images

## Tasks
- [x] Confirm no more use of legacy `generate-sbom` GitHub action
- [x] Remove Dependency Track API key from GitHub org secrets
- [x] Tag repo prior to deletion to preserve Dependency Track code
- [x] Take DB cluster snapshot and export to S3 in the AWS account
- [x] Remove LastPass secrets for Dependency Track
- [x] Destroy Dependency Track AWS infrastructure using `empty` module
- [x] Remove Dependency Track code from repo
- [x] Remove Dependency Track from Pomerium config
